const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('nimbus', {
  githubLogin: () => ipcRenderer.invoke('github-login'),
  getUser: token => ipcRenderer.invoke('get-user', token),
  validateToken: token => ipcRenderer.invoke('validate-token', token),
  setOAuthToken: data => ipcRenderer.invoke('set-oauth-token', data),
  clearOAuthToken: () => ipcRenderer.invoke('clear-oauth-token'),
  list: () => ipcRenderer.invoke('list'),
  upload: folder => ipcRenderer.invoke('upload', folder || ''),
  uploadPaths: data => ipcRenderer.invoke('upload-paths', data),
  zipAndUpload: data => ipcRenderer.invoke('zip-and-upload', data),
  download: data => ipcRenderer.invoke('download', data),
  preview: data => ipcRenderer.invoke('download', { ...data, preview: true }),
  delete: data => ipcRenderer.invoke('delete', data),
  rename: data => ipcRenderer.invoke('rename', data),
  bulkDelete: filenames => ipcRenderer.invoke('bulk-delete', filenames),
  moveFiles: data => ipcRenderer.invoke('move-files', data),
  createFolder: name => ipcRenderer.invoke('create-folder', name),
  deleteFolder: name => ipcRenderer.invoke('delete-folder', name),
  renameFolder: data => ipcRenderer.invoke('rename-folder', data),
  refreshFromGithub: () => ipcRenderer.invoke('refresh-from-github'),
  downloadFolderZip: folderName => ipcRenderer.invoke('download-folder-zip', folderName),
  generateShareLink: data => ipcRenderer.invoke('generate-share-link', data),
  backupDownload: () => ipcRenderer.invoke('backup-download'),
  backupUpload: () => ipcRenderer.invoke('backup-upload'),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  openCache: () => ipcRenderer.invoke('open-cache'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: data => ipcRenderer.invoke('set-settings', data),
  onProgress: fn => ipcRenderer.on('progress', (_, data) => fn(data)),
  onOAuthToken: fn => ipcRenderer.on('oauth-token', (_, token) => fn(token)),
  onShareLink: fn => ipcRenderer.on('share-link', (_, data) => fn(data)),
  onAutoRefresh: fn => ipcRenderer.on('auto-refresh', () => fn()),
  winMinimize: () => ipcRenderer.invoke('win-minimize'),
  winMaximize: () => ipcRenderer.invoke('win-maximize'),
  winClose: () => ipcRenderer.invoke('win-close'),
})
