const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('nimbus', {
  githubLogin: () => ipcRenderer.invoke('github-login'),
  getUser: token => ipcRenderer.invoke('get-user', token),
  validateToken: token => ipcRenderer.invoke('validate-token', token),
  setOAuthToken: data => ipcRenderer.invoke('set-oauth-token', data),
  clearOAuthToken: () => ipcRenderer.invoke('clear-oauth-token'),
  list: () => ipcRenderer.invoke('list'),
  upload: () => ipcRenderer.invoke('upload'),
  uploadPaths: paths => ipcRenderer.invoke('upload-paths', paths),
  download: filename => ipcRenderer.invoke('download', { filename }),
  preview: filename => ipcRenderer.invoke('download', { filename, preview: true }),
  cachePreview: filename => ipcRenderer.invoke('download', { filename, preview: true }),
  delete: filename => ipcRenderer.invoke('delete', filename),
  rename: data => ipcRenderer.invoke('rename', data),
  bulkDelete: filenames => ipcRenderer.invoke('bulk-delete', filenames),
  backupDownload: () => ipcRenderer.invoke('backup-download'),
  backupUpload: () => ipcRenderer.invoke('backup-upload'),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  openCache: () => ipcRenderer.invoke('open-cache'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: data => ipcRenderer.invoke('set-settings', data),
  onProgress: fn => ipcRenderer.on('progress', (_, data) => fn(data)),
  onOAuthToken: fn => ipcRenderer.on('oauth-token', (_, token) => fn(token)),
  winMinimize: () => ipcRenderer.invoke('win-minimize'),
  winMaximize: () => ipcRenderer.invoke('win-maximize'),
  winClose: () => ipcRenderer.invoke('win-close'),
})
